// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UniversityTestAPI.Models
{
    public partial class Faculty
    {
        public Guid FacultyId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public Guid? CollegeId { get; set; }
    }
}